from sqlalchemy import false, true, null

backup = [
  {
    "id": 1,
    "category": "Novel",
    "title": "Geliebter Roboter",
    "series": true,
    "volume": 2,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 10,
    "isbn": 9783453528437,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2016-01-11",
    "payDate": "2021-12-24",
    "startDate": "2022-05-11",
    "endDate": "2022-05-23"
  },
  {
    "id": 2,
    "category": "Technical",
    "title": "Grundkurs C",
    "series": false,
    "volume": 0,
    "author": "Jürgen Wolf René Krooß",
    "publisher": "Rheinwerk Computing",
    "price": 14.9,
    "isbn": 9783836276894,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2020-09-28",
    "payDate": "2022-04-30",
    "startDate": "2022-05-02",
    "endDate": null
  },
  {
    "id": 3,
    "category": "Novel",
    "title": "Solo Leveling",
    "series": true,
    "volume": 5,
    "author": "Chugong",
    "publisher": "Altraverse GmbH",
    "price": 24,
    "isbn": 9783963587528,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-03-21",
    "payDate": "2022-05-20",
    "startDate": "2022-06-05",
    "endDate": "2022-06-08"
  },
  {
    "id": 4,
    "category": "Manga",
    "title": "The Saint's Magic Power is Omnipotent",
    "series": true,
    "volume": 2,
    "author": "Yuka Tachibana",
    "publisher": "Tokyopop",
    "price": 6.99,
    "isbn": 9783842071049,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-02-16",
    "payDate": "2022-05-20",
    "startDate": "2022-06-01",
    "endDate": "2022-06-04"
  },
  {
    "id": 5,
    "category": "Manga",
    "title": "Horimiya",
    "series": true,
    "volume": 16,
    "author": "Hero",
    "publisher": "Egmont Manga",
    "price": 7.5,
    "isbn": 9783770441921,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-03-04",
    "payDate": "2022-05-20",
    "startDate": "2022-05-24",
    "endDate": "2022-05-31"
  },
  {
    "id": 6,
    "category": "Novel",
    "title": "Der Zweihundertjährige",
    "series": true,
    "volume": 3,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 9.99,
    "isbn": 9783453527966,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2014-11-27",
    "payDate": "2022-06-08",
    "startDate": "2022-06-13",
    "endDate": "2022-07-07"
  },
  {
    "id": 7,
    "category": "Manga",
    "title": "The Saint's Magic Power is Omnipotent",
    "series": true,
    "volume": 3,
    "author": "Yuka Tachibana",
    "publisher": "Tokyopop",
    "price": 6.99,
    "isbn": 9783842071056,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2022-06-08",
    "payDate": "2022-07-21",
    "startDate": "2022-07-27",
    "endDate": "2022-08-09"
  },
  {
    "id": 8,
    "category": "Manga",
    "title": "The Saint's Magic Power is Omnipotent",
    "series": true,
    "volume": 4,
    "author": "Yuka Tachibana",
    "publisher": "Tokyopop",
    "price": 6.99,
    "isbn": 9783842071063,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-07-13",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 9,
    "category": "Manga",
    "title": "The Saint's Magic Power is Omnipotent",
    "series": true,
    "volume": 5,
    "author": "Yuka Tachibana",
    "publisher": "Tokyopop",
    "price": 6.99,
    "isbn": 9783842071070,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-10-12",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 10,
    "category": "Manga",
    "title": "Toxic Love Affair",
    "series": true,
    "volume": 1,
    "author": "FLOWERCHILD",
    "publisher": "Tokyopop",
    "price": 7.99,
    "isbn": 9783842070035,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2021-08-11",
    "payDate": "2022-06-08",
    "startDate": "2022-06-08",
    "endDate": "2022-06-12"
  },
  {
    "id": 11,
    "category": "Manga",
    "title": "Toxic Love Affair",
    "series": true,
    "volume": 2,
    "author": "FLOWERCHILD",
    "publisher": "Tokyopop",
    "price": 7.99,
    "isbn": 9783842070042,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2021-11-10",
    "payDate": "2022-06-15",
    "startDate": "2022-07-08",
    "endDate": "2022-07-12"
  },
  {
    "id": 12,
    "category": "Manga",
    "title": "Toxic Love Affair",
    "series": true,
    "volume": 3,
    "author": "FLOWERCHILD",
    "publisher": "Tokyopop",
    "price": 7.99,
    "isbn": 9783842071735,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-02-09",
    "payDate": "2022-06-15",
    "startDate": "2022-07-13",
    "endDate": "2022-07-18"
  },
  {
    "id": 13,
    "category": "Manga",
    "title": "Toxic Love Affair",
    "series": true,
    "volume": 4,
    "author": "FLOWERCHILD",
    "publisher": "Tokyopop",
    "price": 7.99,
    "isbn": 9783842073791,
    "wishlist": false,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-05-11",
    "payDate": "2022-06-15",
    "startDate": "2022-07-19",
    "endDate": "2022-07-26"
  },
  {
    "id": 14,
    "category": "Novel",
    "title": "Solo Leveling",
    "series": true,
    "volume": 6,
    "author": "Chugong",
    "publisher": "Altraverse GmbH",
    "price": 24,
    "isbn": 9783963587535,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2022-06-20",
    "payDate": "2022-07-21",
    "startDate": "2022-07-30",
    "endDate": "2022-08-06"
  },
  {
    "id": 15,
    "category": "Novel",
    "title": "Die Kinder der Zeit",
    "series": true,
    "volume": 1,
    "author": "Adrian Tchaikovsky",
    "publisher": "Heyne Verlag",
    "price": 15.99,
    "isbn": 9783453318984,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2018-02-12",
    "payDate": "2022-07-21",
    "startDate": "2022-09-06",
    "endDate": "2022-09-15"
  },
  {
    "id": 16,
    "category": "Novel",
    "title": "Die Erben der Zeit",
    "series": true,
    "volume": 2,
    "author": "Adrian Tchaikovsky",
    "publisher": "Heyne Verlag",
    "price": 15.99,
    "isbn": 9783453320369,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2020-01-13",
    "payDate": "2022-07-21",
    "startDate": null,
    "endDate": null
  },
  {
    "id": 17,
    "category": "Technical",
    "title": "Du gehörst uns! Die psychologischen Strategien von Facebook, TikTok, Snapchat & Co",
    "series": false,
    "volume": 0,
    "author": "Christian Montag",
    "publisher": "Blessing",
    "price": 20,
    "isbn": 9783896677068,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2021-10-18",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 18,
    "category": "Technical",
    "title": "Der Fürst",
    "series": false,
    "volume": 0,
    "author": "Niccolò Machiavelli",
    "publisher": "Nikol",
    "price": 4.95,
    "isbn": 9783868200218,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2009-02-04",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 19,
    "category": "Technical",
    "title": "Klimaschock: Die extremen wirtschaftlichen Konsequenzen des Klimawandels",
    "series": false,
    "volume": 0,
    "author": "Gernot Wagner",
    "publisher": "Ueberreuter, C.",
    "price": 9.99,
    "isbn": 9783800076499,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-03-24",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 20,
    "category": "Technical",
    "title": "Zehn Gründe, warum du deine Social Media Accounts sofort löschen musst",
    "series": false,
    "volume": 0,
    "author": "Jaron Lanier",
    "publisher": "Atlantik",
    "price": 14,
    "isbn": 9783455004915,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2019-07-04",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 21,
    "category": "Technical",
    "title": "Das große Buch vom Schlaf: Die enorme Bedeutung des Schlafs",
    "series": false,
    "volume": 0,
    "author": "Matthew Walker",
    "publisher": "Goldmann Verlag",
    "price": 13,
    "isbn": 9783442177912,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2018-11-19",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 22,
    "category": "Novel",
    "title": "Die Stahlhöhlen",
    "series": true,
    "volume": 4,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 9.99,
    "isbn": 9783453527942,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2016-05-09",
    "payDate": "2022-07-21",
    "startDate": "2022-08-13",
    "endDate": "2022-09-05"
  },
  {
    "id": 23,
    "category": "Novel",
    "title": "Die göttliche Komödie",
    "series": false,
    "volume": 0,
    "author": "Dante Alighieri",
    "publisher": "Anaconda Verlag",
    "price": 6.95,
    "isbn": 9783938484111,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2005-05-30",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 24,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 1,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216574,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-04-02",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 25,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 2,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216581,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-06-05",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 26,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 3,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216598,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-08-06",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 27,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 4,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216604,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-10-01",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 28,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 5,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216611,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-12-03",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 29,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 6,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216628,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-02-04",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 30,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 7,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216635,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-04-07",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 31,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 8,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216642,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-06-01",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 32,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 9,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216659,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-08-03",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 33,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 10,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216666,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-10-06",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 34,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 11,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216673,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-12-01",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 35,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 12,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216680,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-02-02",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 36,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 13,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216697,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-04-06",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 37,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 14,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216703,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-06-10",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 38,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 15,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216710,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-08-03",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 39,
    "category": "Manga",
    "title": "Wolf Girl & Black Prince",
    "series": true,
    "volume": 16,
    "author": "Ayuko Hatta",
    "publisher": "Kazé Manga",
    "price": 6.95,
    "isbn": 9782889216710,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-10-05",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 40,
    "category": "Novel",
    "title": "1984",
    "series": false,
    "volume": 0,
    "author": "George Orwell",
    "publisher": "Nikol",
    "price": 7.95,
    "isbn": 9783868206074,
    "wishlist": false,
    "gift": true,
    "borrow": false,
    "releaseDate": "2021-01-11",
    "payDate": "2022-07-21",
    "startDate": null,
    "endDate": null
  },
  {
    "id": 41,
    "category": "Novel",
    "title": "Die nackte Sonne",
    "series": true,
    "volume": 5,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 8.99,
    "isbn": 9783453528444,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2016-09-12",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 42,
    "category": "Novel",
    "title": "Solo Leveling",
    "series": true,
    "volume": 7,
    "author": "Chugong",
    "publisher": "Altraverse GmbH",
    "price": 24,
    "isbn": 9783963587542,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-09-17",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 43,
    "category": "Manga",
    "title": "Bloom into you: Anthologie",
    "series": true,
    "volume": 1,
    "author": "Nio Nakatani",
    "publisher": "Carlsen Manga",
    "price": 7.5,
    "isbn": 9783551713155,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-10-25",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 44,
    "category": "Manga",
    "title": "Bloom into you: Anthologie",
    "series": true,
    "volume": 2,
    "author": "Nio Nakatani",
    "publisher": "Carlsen Manga",
    "price": 7.5,
    "isbn": 9783551713162,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2023-01-31",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 45,
    "category": "Novel",
    "title": "Der Aufbruch zu den Sternen",
    "series": true,
    "volume": 6,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 11,
    "isbn": 9783453321885,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-04-11",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 46,
    "category": "Novel",
    "title": "Das galaktische Imperium",
    "series": true,
    "volume": 7,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 11,
    "isbn": 9783453321038,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2022-03-08",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 47,
    "category": "Novel",
    "title": "Sterne wie Staub",
    "series": true,
    "volume": 8,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 8.99,
    "isbn": 9783453528406,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-06-15",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 48,
    "category": "Novel",
    "title": "Ströme im All",
    "series": true,
    "volume": 9,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 8.99,
    "isbn": 9783453528390,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-08-10",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 49,
    "category": "Novel",
    "title": "Die Rettung des Imperiums",
    "series": true,
    "volume": 11,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 9.99,
    "isbn": 9783453528376,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2014-10-13",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 50,
    "category": "Novel",
    "title": "Das Foundation Projekt",
    "series": true,
    "volume": 12,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 9.99,
    "isbn": 9783453528451,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2014-04-12",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 51,
    "category": "Novel",
    "title": "Die Foundation-Trilogie: Foundation / Foundation und Imperium / Zweite Foundation",
    "series": true,
    "volume": 13,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 14,
    "isbn": 9783453318670,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2017-08-14",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 52,
    "category": "Novel",
    "title": "Die Suche nach der Erde",
    "series": true,
    "volume": 14,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 14,
    "isbn": 9783453316324,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2014-12-08",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 53,
    "category": "Novel",
    "title": "Die Rückkehr zur Erde",
    "series": true,
    "volume": 15,
    "author": "Isaac Asimov",
    "publisher": "Heyne Verlag",
    "price": 9.99,
    "isbn": 9783453316331,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2015-03-09",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 54,
    "category": "Novel",
    "title": "Schöne Neue Welt",
    "series": false,
    "volume": 0,
    "author": "Aldous Huxley",
    "publisher": "Fischer Taschenbuch",
    "price": 12,
    "isbn": 9783596905737,
    "wishlist": true,
    "gift": false,
    "borrow": false,
    "releaseDate": "2014-03-06",
    "payDate": null,
    "startDate": null,
    "endDate": null
  },
  {
    "id": 55,
    "category": "Novel",
    "title": "Der Wüstenplanet",
    "series": true,
    "volume": 1,
    "author": "Frank Herbert",
    "publisher": "Heyne Verlag",
    "price": 12.99,
    "isbn": 9783453186835,
    "wishlist": true,
    "gift": false,
    "borrow": true,
    "releaseDate": "2021-08-09",
    "payDate": null,
    "startDate": null,
    "endDate": null
  }
]