version: "3.11"

services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: library
      # So you don't have to use root, but you can if you like
      MYSQL_USER: libraryAPI
      # You can use whatever password you like
      MYSQL_PASSWORD: hallowelt
      # Password for root access
      MYSQL_ROOT_PASSWORD: 9sonne99
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'

  fastapi:
    build: ./library_API
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=mysql+pymysql://libraryAPI:hallowelt@database/library

    depends_on:
      - database