version: "3.11"

services:
  fastapi:
    build: ./library_API
    ports:
      - "5000:5000"
    environment:
      # Format: mysql+pymysql://<user>:<passwort>@<db-host>:3306/<datenbankname>
      - DATABASE_URL=${DATABASE_URL:-mysql+pymysql://libraryAPI:hallowelt@mysql:3306/library}
    networks:
      - default
      - mysql_default

networks:
  mysql_default:
    external: true
